export default {
  PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
  PRODUCT_UPDATE_REQUEST: 'ADD_PRODUCT_UPDATE_REQUEST',
  PRODUCT_UPDATE_SUCCESS: 'ADD_PRODUCT_UPDATE_SUCCESS',
  PRODUCT_UPDATE_FAILURE: 'ADD_PRODUCT_UPDATE_FAILURE',
};
